"""add google_id nullable password

Revision ID: c03fb26cb947
Revises: 
Create Date: 2026-05-21 01:54:05.295581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c03fb26cb947'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('google_id', sa.String(), nullable=True))
    op.alter_column('players', 'password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_players_google_id'), 'players', ['google_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_players_google_id'), table_name='players')
    op.alter_column('players', 'password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('players', 'google_id')
    # ### end Alembic commands ###
